[package]
name = "mdbook-extended"
authors = ["Patrick Lamprecht <lamprecht.patrick1@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dev-dependencies]
mdbook = "0.4.25"
mdbook-toc = "0.11.0"
mdbook-mermaid = "0.12.6"
mdbook-admonish = "1.8.0"
mdbook-linkcheck = "0.7.7"
mdbook-pdf = "0.1.3"